name: TestNG CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: windows-latest  # Use windows-latest if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}
            
      - name: Run Specific TestNG Suite (E2E)
        run: mvn test -DsuiteXmlFile=E2ETestingOfStar.xml
        
      - name: Build & Run TestNG Tests
        run: mvn clean test
