name: TestNG CI

on:
  push:
    branches:
      - main
      
jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ${{ runner.workspace }}\.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}

      - name: Build and Run Tests
        run: |
          ./mvnw clean test || mvn clean test
